---
- hosts: controllers:workers
  roles:
    - ansible/roles/k8s-transfer-conf
    - ansible/roles/k8s-bootstrap-etcd
    - ansible/roles/k8s-bootstrap-control-plane
    - ansible/roles/k8s-bootstrap-workers
  vars:
    etcd_servers:
      - controller-1: 10.240.0.11
      - controller-2: 10.240.0.12
      - controller-3: 10.240.0.13
    pod_cidr:
      - worker-1: 10.200.1.0/24
      - worker-2: 10.200.2.0/24
      - worker-3: 10.200.3.0/24
    kubernetes_version: 1.22.2
    remote_path: /home/{{ ansible_ssh_user }}/k8s-thw
    temp_dir: /tmp
    kubernetes_public_address: 35.238.95.224
    kube_apiserver_count: 3
    cluster_dns: "10.32.0.10"